
import Client.*;
import Server.*;
import java.awt.AWTException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;

/**
 *
 * @author hp DEVELOPED BY: ANIQUA TABASSUM
 */
public class ConnectifyFirstPage extends javax.swing.JFrame {

    /**
     * Creates new form TeamviewerFirstPage
     */
    public ConnectifyFirstPage() {
        initComponents();
        group.add(clientButton);
        group.add(serverButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teamviewerLabel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JLabel();
        chooceToContinueAs = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        clientButton = new javax.swing.JRadioButton();
        serverButton = new javax.swing.JRadioButton();
        goButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        teamviewerLabel.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CONNECTIFY");
        jLabel1.setToolTipText("Welcome to TEAMVIEWER");

        exitLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(0, 0, 0));
        exitLabel.setText("  X");
        exitLabel.setToolTipText("Close window\n");
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });

        minimizeLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        minimizeLabel.setForeground(new java.awt.Color(0, 0, 0));
        minimizeLabel.setText("-");
        minimizeLabel.setToolTipText("Minimize window");
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout teamviewerLabelLayout = new javax.swing.GroupLayout(teamviewerLabel);
        teamviewerLabel.setLayout(teamviewerLabelLayout);
        teamviewerLabelLayout.setHorizontalGroup(
            teamviewerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teamviewerLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(minimizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        teamviewerLabelLayout.setVerticalGroup(
            teamviewerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teamviewerLabelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(teamviewerLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minimizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        chooceToContinueAs.setBackground(new java.awt.Color(255, 255, 255));
        chooceToContinueAs.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("What do you want to continue as?");

        clientButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        clientButton.setForeground(new java.awt.Color(0, 0, 0));
        clientButton.setText("Client");
        clientButton.setToolTipText("Your screen will be visible to the Server and they might control your PC, if you give them the permission to do so");
        clientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientButtonActionPerformed(evt);
            }
        });

        serverButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        serverButton.setForeground(new java.awt.Color(0, 0, 0));
        serverButton.setText("Server");
        serverButton.setToolTipText("You will be able to see the screen of your client and might be able to control that PC, if your client permits you to do so");
        serverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverButtonActionPerformed(evt);
            }
        });

        goButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        goButton.setForeground(new java.awt.Color(0, 0, 0));
        goButton.setText("GO");
        goButton.setToolTipText("Click to proceed");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chooceToContinueAsLayout = new javax.swing.GroupLayout(chooceToContinueAs);
        chooceToContinueAs.setLayout(chooceToContinueAsLayout);
        chooceToContinueAsLayout.setHorizontalGroup(
            chooceToContinueAsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooceToContinueAsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clientButton)
                .addGap(74, 74, 74)
                .addComponent(serverButton)
                .addGap(82, 82, 82))
            .addGroup(chooceToContinueAsLayout.createSequentialGroup()
                .addGroup(chooceToContinueAsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chooceToContinueAsLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(chooceToContinueAsLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        chooceToContinueAsLayout.setVerticalGroup(
            chooceToContinueAsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooceToContinueAsLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(chooceToContinueAsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientButton))
                .addGap(35, 35, 35)
                .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(teamviewerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(chooceToContinueAs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(teamviewerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(chooceToContinueAs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     String continuingAs = null;//this variable is used to store the information of whether the user wants to continue as "Client" or "Server"
    ButtonGroup group = new ButtonGroup();//this variable has two buttons, the "Client" button and the "Server" button
    //This method closes the software when the "exit button" is clicked
    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked
    //This method minimizes the software when the "minimize button" is clicked
    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeLabelMouseClicked
    //this method makes the user the "Client" for the session  
    private void clientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientButtonActionPerformed
        // TODO add your handling code here:
        if (clientButton.isSelected()) {
            serverButton.setSelected(false);
            continuingAs = "client";
        }
    }//GEN-LAST:event_clientButtonActionPerformed
 //this method makes the user the "Server" for the session 
    private void serverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverButtonActionPerformed
        // TODO add your handling code here:
        if (serverButton.isSelected()) {
            clientButton.setSelected(false);
            continuingAs = "server";

        }
    }//GEN-LAST:event_serverButtonActionPerformed
     //this method directs the user to the next page, that may be the Client's page or the Server's page, depending on his choice
    
    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        // TODO add your handling code here:
        if (continuingAs.equalsIgnoreCase("server")) {

            ServerFirstPage sPage;
            try {
                sPage = new ServerFirstPage();
                sPage.setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(ConnectifyFirstPage.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                new StartServer();
            } catch (IOException ex) {
                Logger.getLogger(ConnectifyFirstPage.class.getName()).log(Level.SEVERE, null, ex);
            }

            this.hide();
        } else {
            try {
                ClientFirstPage cPage = new ClientFirstPage();
                cPage.setVisible(true);
                this.hide();
            } catch (IOException ex) {
                Logger.getLogger(ConnectifyFirstPage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (AWTException ex) {
                Logger.getLogger(ConnectifyFirstPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_goButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConnectifyFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConnectifyFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConnectifyFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConnectifyFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConnectifyFirstPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chooceToContinueAs;
    private javax.swing.JRadioButton clientButton;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JRadioButton serverButton;
    private javax.swing.JPanel teamviewerLabel;
    // End of variables declaration//GEN-END:variables
}
